samnixon87/le-chariot

Gemfile
Gemfile.lock
app/models/issue.rb
app/models/user.rb
db/migrate/20230306161408_remove_issue_from_channel.rb
db/migrate/20230306161409_add_first_name_to_user.rb
db/schema.rb
db/seeds.rb

Models and seeds file changed. Can now run rails db:seed without tears falling onto my keyboard

Fixed models and seed file

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_bubble.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_card_grid.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Add a lot of css partials so we can work on them all together

Add partials for css components

---

db/seeds.rb

user_id and channel_id for issue are now taken from variables so that we won't have to do db:reset for it to work every time

Added user_id and channel_id in to variables for issue

---

app/channels/channel_channel.rb
app/controllers/channels_controller.rb
app/controllers/chatroom_messages_controller.rb
app/javascript/controllers/channel_subscription_controller.js
app/javascript/controllers/index.js
app/models/channel.rb
app/models/chatroom_message.rb
app/views/channels/show.html.erb
app/views/chatroom_messages/_chatroom_message.html.erb
config/routes.rb
db/migrate/20230306161410_create_chatroom_messages.rb
db/migrate/20230306161411_add_nickname_to_users.rb
db/schema.rb
package.json
test/channels/channel_channel_test.rb
test/controllers/channels_controller_test.rb
test/controllers/chatroom_messages_controller_test.rb
test/models/chatroom_message_test.rb
yarn.lock

Chat is working now but without auto scrolling, form reset and unsubscribe but will work on it now

Chat functionality

---

app/assets/stylesheets/components/_chat_window.scss
app/assets/stylesheets/components/_chatroom.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_issue_list.scss
app/assets/stylesheets/components/_message_column.scss
app/views/channels/show.html.erb
app/views/issues/_show.erb
app/views/issues/show.html.erb

- First cut of chat UI
- TO DO: Message section is currently not complete

First cut of chat UI

---

app/assets/stylesheets/components/_message_column.scss
app/views/issues/show.html.erb

Chat is now sticky, fit to view height

Fixed sticky position for chat bar

---

app/assets/stylesheets/components/_chatroom.scss
app/assets/stylesheets/components/_message_column.scss
app/views/channels/show.html.erb
app/views/issues/_show.erb
app/views/issues/show.html.erb
app/views/messages/_message.erb

- Fixed chat input
- Added description to the issue
- vh's are a mess. Will refactor tomorrow/next week

Fixed sticky chat

---

app/assets/stylesheets/components/_issue_list.scss
app/assets/stylesheets/components/_message_column.scss
app/views/issues/_index.html.erb
app/views/issues/_show.erb
app/views/messages/_message.erb

- Adjust where actions render on the chat message. Thumbs up is now on the bottom.
- Move create message button to the top
- Add some delimiters (colourful lines across the top of the message and issues lists

Fixed chat action ui placement. Fixed create message placement

---

app/assets/stylesheets/components/_channel_column.scss
app/views/channels/_index.html.erb

- Reinstate div css
- Fix transform animation

Fix channel ui

---

app/views/issues/_index.html.erb
app/views/issues/_list.html.erb

- Fix margin / padding on issues bar

Fix padding/margins on issues bar

---

db/seeds.rb

improved seed, added issues and new messages

improved seed, added issues and new messages

---

db/seeds.rb

added destroying messages

---

app/assets/stylesheets/components/_chat_window.scss
app/assets/stylesheets/components/_message_column.scss
app/views/channels/show.html.erb

Minor update to css - fixes margin issue

Bug: Fix margin issue

---

app/views/issues/_index.html.erb
app/views/issues/_list.html.erb

added issue and message counters

added issue and message counters

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_message_column.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/javascript/controllers/dark_mode_controller.js
app/javascript/controllers/highlight_controller.js
app/javascript/controllers/index.js
app/views/issues/_show.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
package.json
yarn.lock

updated dark mode and syntax highlighting

updated dark mode and syntax highlighting

---

app/controllers/callbacks_controller.rb
app/controllers/channels_controller.rb
app/javascript/application.js
app/javascript/controllers/issue_subscription_controller.js
app/views/issues/_index.html.erb
app/views/issues/_list.html.erb
app/views/users/show.html.erb

- Orders messages by most messages
- Adds nickname from Github to profile

Order issues by most messages + Profile update

---

app/views/devise/registrations/edit.html.erb
app/views/issues/new.html.erb

minor meta tags improvements

---

app/javascript/controllers/issue_subscription_controller.js
app/models/message.rb
app/views/issues/_show.erb
db/migrate/20230315101112_drop_content_from_messages.rb
db/schema.rb
db/seeds.rb

- Made some changes to model to fix the action-text rendering issue
- Enabled `enter` to send a message

Fix actiontext input

---

app/views/messages/_message.erb

like counter at bottom of message. Page still needs to be refreshed to show

Like count

---

app/views/shared/_navbar.html.erb

- One line fix for logo centering issue

Fixed logo centering

---

app/views/layouts/application.html.erb

Improved meta

---

app/views/messages/_message.erb
app/views/users/show.html.erb

- Add a likes tab to profile page

Add likes to profile

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_home.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_login.scss
app/assets/stylesheets/components/_message_column.scss
app/assets/stylesheets/components/_profile.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/devise/sessions/new.html.erb
app/views/issues/_index.html.erb
app/views/issues/_show.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb

minor css improvements based on the feedback

minor css improvements based on the feedback

---

db/seeds.rb

- Improved seed
- Still a WIP, but better

Improved seed. Still a WIP

---

app/views/issues/_list.html.erb

- Previously we had a @issue.id check on the issues list to add a class 
- There are better ways to do that and it's not the best feature.
- Removing

Removed dumb code I wrote

---

app/jobs/ai_request_job.rb

new ai prompt
